// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NF_8x2gBeqzZT2EhQC3asTKvh2BfKKE',
    appId: '1:851281868549:web:7dd7087d6cba33de9e296c',
    messagingSenderId: '851281868549',
    projectId: 'greenify-2fce6',
    authDomain: 'greenify-2fce6.firebaseapp.com',
    storageBucket: 'greenify-2fce6.firebasestorage.app',
    measurementId: 'G-E6NMJK2GPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQxAYF8gn-DFIfRFHCPhkbjTYC_tR914',
    appId: '1:851281868549:android:ecc850f1745c34739e296c',
    messagingSenderId: '851281868549',
    projectId: 'greenify-2fce6',
    storageBucket: 'greenify-2fce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK4rVogb3zYVpqsU1g2vx6IimOnehLKRs',
    appId: '1:851281868549:ios:cc717ca1050db9689e296c',
    messagingSenderId: '851281868549',
    projectId: 'greenify-2fce6',
    storageBucket: 'greenify-2fce6.firebasestorage.app',
    iosBundleId: 'com.example.greenify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK4rVogb3zYVpqsU1g2vx6IimOnehLKRs',
    appId: '1:851281868549:ios:cc717ca1050db9689e296c',
    messagingSenderId: '851281868549',
    projectId: 'greenify-2fce6',
    storageBucket: 'greenify-2fce6.firebasestorage.app',
    iosBundleId: 'com.example.greenify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1NF_8x2gBeqzZT2EhQC3asTKvh2BfKKE',
    appId: '1:851281868549:web:a2fbe3c04a1d35769e296c',
    messagingSenderId: '851281868549',
    projectId: 'greenify-2fce6',
    authDomain: 'greenify-2fce6.firebaseapp.com',
    storageBucket: 'greenify-2fce6.firebasestorage.app',
    measurementId: 'G-WJ9RF07G65',
  );
}
